<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // --- USERS ---
        $users = [
            [
                'id' => 1,
                'name' => 'Eduards Megnis',
                'email' => 'eduards.megnis@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$6hgaDzO/rc1UIOtLB6dGaOaxrpQ5vEzui8qw4znjspfQMAGs8..Ae',
                'remember_token' => null,
                'created_at' => '2026-03-24 10:09:06',
                'updated_at' => '2026-03-26 07:27:35',
            ],
            [
                'id' => 2,
                'name' => 'Andris Mārtiņsons',
                'email' => 'martinsons.andris@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$SnGZ56SX1HJJXHhrY8KAj.mmVF.l.4NmeFPLtIV/k1bgrzsNUUhA6',
                'remember_token' => null,
                'created_at' => '2026-03-24 10:18:28',
                'updated_at' => '2026-03-24 10:18:28',
            ],
            [
                'id' => 3,
                'name' => 'Jānis Stumbrs',
                'email' => 'janis.stumbrs@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$iexgbXXBGq16cSnGH.DEL.7RvR6Dc2lUHnJ6.B1uxWBu0xirVGv.W',
                'remember_token' => null,
                'created_at' => '2026-03-24 10:43:32',
                'updated_at' => '2026-03-26 07:27:08',
            ],
            [
                'id' => 4,
                'name' => 'Otto Bergmanis',
                'email' => 'otto.bergmanis@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$/ADiTYxinwiUZ9HKHAsj8OeptwKye/xobxvVyvMsSkfm9K5yb/KBi',
                'remember_token' => null,
                'created_at' => '2026-03-24 11:28:42',
                'updated_at' => '2026-03-24 13:57:15',
            ],
            [
                'id' => 5,
                'name' => 'Enriko Bērzkalns',
                'email' => 'enriko.berzkalns@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$0R8qF9SCqv08444X5hQq0.bzzIYkZJ6p.VYneNM65KnGG7QRFLAay',
                'remember_token' => null,
                'created_at' => '2026-03-26 07:24:51',
                'updated_at' => '2026-03-26 07:24:51',
            ],
        ];

        DB::table('users')->insert($users);

        // --- BOOKS ---
        $books = [
            [
                'id' => 1,
                'user_id' => 1,
                'title' => 'SweetBonanza1000',
                'author' => 'Pragmatic',
                'genre' => 'Romāns',
                'language' => 'English',
                'condition' => 'Good',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 07:00:00',
                'updated_at' => '2026-03-27 07:00:00',
            ],
            [
                'id' => 2,
                'user_id' => 1,
                'title' => 'DuckHunters',
                'author' => 'NoLimitCity',
                'genre' => 'Klasika',
                'language' => 'Latviešu',
                'condition' => 'Fair',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 07:00:00',
                'updated_at' => '2026-03-27 07:00:00',
            ],
            [
                'id' => 3,
                'user_id' => 2,
                'title' => 'XmasDrop',
                'author' => 'Hacksaw',
                'genre' => 'Bērnu grāmatas',
                'language' => 'English',
                'condition' => 'New',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 07:00:00',
                'updated_at' => '2026-03-27 09:00:00',
            ],
            [
                'id' => 4,
                'user_id' => 2,
                'title' => 'DiamondMole',
                'author' => 'Hacksaw',
                'genre' => 'Romāns',
                'language' => 'Latviešu',
                'condition' => 'Worn',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 07:00:00',
                'updated_at' => '2026-03-27 07:00:00',
            ],
            [
                'id' => 5,
                'user_id' => 1,
                'title' => 'GatesOfOlympusSuperScatter',
                'author' => 'Pragmatic',
                'genre' => 'Romāns',
                'language' => 'English',
                'condition' => 'Good',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 07:00:00',
                'updated_at' => '2026-03-27 09:00:00',
            ],
            [
                'id' => 6,
                'user_id' => 2,
                'title' => 'BigBambook',
                'author' => 'PushGaming',
                'genre' => 'Klasika',
                'language' => 'Latviešu',
                'condition' => 'New',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 07:00:00',
                'updated_at' => '2026-03-27 07:00:00',
            ],
            [
                'id' => 7,
                'user_id' => 3,
                'title' => 'SugarRush',
                'author' => 'Pragmatic',
                'genre' => 'Zinātne',
                'language' => 'Русский',
                'condition' => 'Worn',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 07:00:00',
                'updated_at' => '2026-03-27 12:00:00',
            ],
            [
                'id' => 8,
                'user_id' => 3,
                'title' => 'Ragnarok',
                'author' => 'Slotmill',
                'genre' => 'Bērnu grāmatas',
                'language' => 'Latviešu',
                'condition' => 'New',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 07:00:00',
                'updated_at' => '2026-03-27 07:00:00',
            ],
            [
                'id' => 9,
                'user_id' => 4,
                'title' => 'SeaMen',
                'author' => 'NoLimitCity',
                'genre' => 'Trillenis',
                'language' => 'Latviešu',
                'condition' => 'Fair',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 07:00:00',
                'updated_at' => '2026-03-27 12:00:00',
            ],
            [
                'id' => 10,
                'user_id' => 4,
                'title' => 'BarnBusters',
                'author' => 'PlayNGo',
                'genre' => 'Romāns',
                'language' => 'Русский',
                'condition' => 'Good',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 07:00:00',
                'updated_at' => '2026-03-27 07:00:00',
            ],
            [
                'id' => 11,
                'user_id' => 4,
                'title' => 'BookOfRa',
                'author' => 'Novamatic',
                'genre' => 'Dzeja',
                'language' => 'English',
                'condition' => 'Good',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 08:00:00',
                'updated_at' => '2026-03-27 12:00:00',
            ],
            [
                'id' => 12,
                'user_id' => 5,
                'title' => 'BookOfRaDeluxe',
                'author' => 'Novamatic',
                'genre' => 'Zinātne',
                'language' => 'English',
                'condition' => 'Good',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 08:00:00',
                'updated_at' => '2026-03-27 08:00:00',
            ],
            [
                'id' => 13,
                'user_id' => 3,
                'title' => 'CrazyTime',
                'author' => 'Evolution',
                'genre' => 'Vēsture',
                'language' => 'English',
                'condition' => 'Fair',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 08:00:00',
                'updated_at' => '2026-03-27 09:00:00',
            ],
            [
                'id' => 14,
                'user_id' => 5,
                'title' => 'BisonBattle',
                'author' => 'PushGaming',
                'genre' => 'Vēsture',
                'language' => 'Русский',
                'condition' => 'New',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 08:00:00',
                'updated_at' => '2026-03-27 08:00:00',
            ],
            [
                'id' => 15,
                'user_id' => 5,
                'title' => 'BigBamboo2',
                'author' => 'PushGaming',
                'genre' => 'Vēsture',
                'language' => 'English',
                'condition' => 'New',
                'status' => 'Available',
                'description' => null,
                'created_at' => '2026-03-27 08:00:00',
                'updated_at' => '2026-03-27 08:00:00',
            ],
        ];

        DB::table('books')->insert($books);
    }
}